<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $actings = [
            ['id' => '1', 'acting' => 'Acervos'],
            ['id' => '2', 'acting' => 'Agência de casting'],
            ['id' => '3', 'acting' => 'Animação/Animador'],
            ['id' => '4', 'acting' => 'Animação/Assistente'],
            ['id' => '5', 'acting' => 'Animação/Assistente de Diretor'],
            ['id' => '6', 'acting' => 'Animação/Diretor'],
            ['id' => '7', 'acting' => 'Animação/Estagiário'],
            ['id' => '8', 'acting' => 'Apoio ao trânsito'],
            ['id' => '9', 'acting' => 'Arte/Aderecista'],
            ['id' => '10', 'acting' => 'Arte/Assistente de Cabeleireiro'],
            ['id' => '11', 'acting' => 'Arte/Assistente de Cenógrafo'],
            ['id' => '12', 'acting' => 'Arte/Assistente de Diretor'],
            ['id' => '13', 'acting' => 'Arte/Assistente de Figurinista'],
            ['id' => '14', 'acting' => 'Arte/Assistente de Maquiador'],
            ['id' => '15', 'acting' => 'Arte/Assistente de Produtor de Objetos'],
            ['id' => '16', 'acting' => 'Arte/Cabeleireiro'],
            ['id' => '17', 'acting' => 'Arte/Cenógrafo'],
            ['id' => '18', 'acting' => 'Arte/Contrarregra'],
            ['id' => '19', 'acting' => 'Arte/Costureiro'],
            ['id' => '20', 'acting' => 'Arte/Diretor'],
            ['id' => '21', 'acting' => 'Arte/Figurinista'],
            ['id' => '22', 'acting' => 'Arte/Maquiador'],
            ['id' => '23', 'acting' => 'Arte/Produtor'],
            ['id' => '24', 'acting' => 'Arte/Produtor de Objetos'],
            ['id' => '25', 'acting' => 'Assessoria de imprensa'],
            ['id' => '26', 'acting' => 'Assessoria jurídica'],
            ['id' => '27', 'acting' => 'Assistência de produção'],
            ['id' => '28', 'acting' => 'Assistência de SET'],
            ['id' => '29', 'acting' => 'Camareiro/Guada-roupeiro'],
            ['id' => '30', 'acting' => 'Catering'],
            ['id' => '31', 'acting' => 'Centro de Eventos'],
            ['id' => '32', 'acting' => 'Contabilidade'],
            ['id' => '33', 'acting' => 'Direção/Continuísta'],
            ['id' => '34', 'acting' => 'Direção de atores'],
            ['id' => '35', 'acting' => 'Direção de cena/Estagiário'],
            ['id' => '36', 'acting' => 'Direção/Diretor'],
            ['id' => '37', 'acting' => 'Diretor/1º Assistente de Direção'],
            ['id' => '38', 'acting' => 'Diretor/2º Assistente de Direção'],
            ['id' => '39', 'acting' => 'Diretor/3º Assistente de Direção'],
            ['id' => '40', 'acting' => 'Edição/Pós-produção'],
            ['id' => '41', 'acting' => 'Efeitos especiais'],
            ['id' => '42', 'acting' => 'Efeitos especiais/Assistente'],
            ['id' => '43', 'acting' => 'Efeitos especiais/Técnico'],
            ['id' => '44', 'acting' => 'Elenco/Coordenador'],
            ['id' => '45', 'acting' => 'Elenco/Preparador'],
            ['id' => '46', 'acting' => 'Elenco/Produtor'],
            ['id' => '47', 'acting' => 'Elétrica/Assistente'],
            ['id' => '48', 'acting' => 'Elétrica/Eletricista'],
            ['id' => '49', 'acting' => 'Elétrica/Gaffer'],
            ['id' => '50', 'acting' => 'Elétrica/Operador de Gerador'],
            ['id' => '51', 'acting' => 'Entidades e empresas parceiras'],
            ['id' => '52', 'acting' => 'Espaço para Eventos'],
            ['id' => '53', 'acting' => 'Estúdios'],
            ['id' => '54', 'acting' => 'Fotografia/1º Assistente de Câmera'],
            ['id' => '55', 'acting' => 'Fotografia/2º Assistente de Câmera'],
            ['id' => '56', 'acting' => 'Fotografia/Estagiário'],
            ['id' => '57', 'acting' => 'Fotografia/Foquista'],
            ['id' => '58', 'acting' => 'Fotografia/Operador de Câmera'],
            ['id' => '59', 'acting' => 'Fotografia/Operador de drone'],
            ['id' => '60', 'acting' => 'Fotografia/Operador de vídeo assistente'],
            ['id' => '61', 'acting' => 'Fotografia Still/Fotógrafo'],
            ['id' => '62', 'acting' => 'Fotografia subaquática/Fotógrafo'],
            ['id' => '63', 'acting' => 'Gastronomia/Bar'],
            ['id' => '64', 'acting' => 'Gastronomia/Bistrô'],
            ['id' => '65', 'acting' => 'Gastronomia/Brewpub'],
            ['id' => '66', 'acting' => 'Gastronomia/Buffet/Catering'],
            ['id' => '67', 'acting' => 'Gastronomia/Café'],
            ['id' => '68', 'acting' => 'Gastronomia/Casas Noturnas'],
            ['id' => '69', 'acting' => 'Gastronomia/Choperia'],
            ['id' => '70', 'acting' => 'Gastronomia/Churrascaria'],
            ['id' => '71', 'acting' => 'Gastronomia/Coffee-shop'],
            ['id' => '72', 'acting' => 'Gastronomia/Confeiteria'],
            ['id' => '73', 'acting' => 'Gastronomia/Delivery'],
            ['id' => '74', 'acting' => 'Gastronomia/Doceria'],
            ['id' => '75', 'acting' => 'Gastronomia/Drinqueria'],
            ['id' => '76', 'acting' => 'Gastronomia/Fast Food'],
            ['id' => '77', 'acting' => 'Gastronomia/Food Truck'],
            ['id' => '78', 'acting' => 'Gastronomia/Galeteria'],
            ['id' => '79', 'acting' => 'Gastronomia/Gastronomia Itinerante'],
            ['id' => '80', 'acting' => 'Gastronomia/Gastronomita/Itinerante'],
            ['id' => '81', 'acting' => 'Gastronomia/Hamburgueira'],
            ['id' => '82', 'acting' => 'Gastronomia/Hotel'],
            ['id' => '83', 'acting' => 'Gastronomia/Lancheria'],
            ['id' => '84', 'acting' => 'Gastronomia/Loja de Conveniência'],
            ['id' => '85', 'acting' => 'Gastronomia/Mercado'],
            ['id' => '86', 'acting' => 'Gastronomia/Outros'],
            ['id' => '87', 'acting' => 'Gastronomia/Padaria'],
            ['id' => '88', 'acting' => 'Gastronomia/Pastelaria'],
            ['id' => '89', 'acting' => 'Gastronomia/Pizzaria'],
            ['id' => '90', 'acting' => 'Gastronomia/Pub'],
            ['id' => '91', 'acting' => 'Gastronomia/Quiosque'],
            ['id' => '92', 'acting' => 'Gastronomia/Restaurante'],
            ['id' => '93', 'acting' => 'Gastronomia/Restaurante clássico/internacional'],
            ['id' => '94', 'acting' => 'Gastronomia/Restaurante Comida Saudável'],
            ['id' => '95', 'acting' => 'Gastronomia/Restaurante de empresa'],
            ['id' => '96', 'acting' => 'Gastronomia/Snack-bar'],
            ['id' => '97', 'acting' => 'Gastronomia/Sorveteria'],
            ['id' => '98', 'acting' => 'Gastronomia/Sushi'],
            ['id' => '99', 'acting' => 'Gastronomia/Temakeria'],
            ['id' => '100', 'acting' => 'Hospedagem'],
            ['id' => '101', 'acting' => 'Hospedagem/Cama e café'],
            ['id' => '102', 'acting' => 'Hospedagem/Flat/apart-hotel'],
            ['id' => '103', 'acting' => 'Hospedagem/Hotel'],
            ['id' => '104', 'acting' => 'Hospedagem/Hotel fazenda'],
            ['id' => '105', 'acting' => 'Hospedagem/Hotel Turístico'],
            ['id' => '106', 'acting' => 'Hospedagem/Outros'],
            ['id' => '107', 'acting' => 'Hospedagem/Pousada'],
            ['id' => '108', 'acting' => 'Hospedagem/Resort'],
            ['id' => '109', 'acting' => 'Limpeza'],
            ['id' => '110', 'acting' => 'Locação de equipamentos'],
            ['id' => '111', 'acting' => 'Locação de objetos/Figurino'],
            ['id' => '112', 'acting' => 'Locação de veículos'],
            ['id' => '113', 'acting' => 'Making of/Fotógrafo'],
            ['id' => '114', 'acting' => 'Maquiagem/Assistente'],
            ['id' => '115', 'acting' => 'Maquiagem de efeitos especiais/Maquiador'],
            ['id' => '116', 'acting' => 'Maquiagem/Maquiador'],
            ['id' => '117', 'acting' => 'Maquinária/Assistente'],
            ['id' => '118', 'acting' => 'Maquinária/Estagiário'],
            ['id' => '119', 'acting' => 'Maquinária/Maquinista-Chefe'],
            ['id' => '120', 'acting' => 'Pós-produção/Assistente de editor'],
            ['id' => '121', 'acting' => 'Pós-produção/Editor'],
            ['id' => '122', 'acting' => 'Pós-produção/Estagiário'],
            ['id' => '123', 'acting' => 'Pós-produção/Finalizador'],
            ['id' => '124', 'acting' => 'Pós-produção/Produtor de finalização'],
            ['id' => '125', 'acting' => 'Produção/Assistente de platô'],
            ['id' => '126', 'acting' => 'Produção audiovisual'],
            ['id' => '127', 'acting' => 'Produção/Coordenador'],
            ['id' => '128', 'acting' => 'Produção de casting/Assistente'],
            ['id' => '129', 'acting' => 'Produção de casting/Produtor'],
            ['id' => '130', 'acting' => 'Produção de elenco/Assistente'],
            ['id' => '131', 'acting' => 'Produção de elenco/Produtor'],
            ['id' => '132', 'acting' => 'Produção de frente/Assistente'],
            ['id' => '133', 'acting' => 'Produção de frente/Produtor'],
            ['id' => '134', 'acting' => 'Produção de locação/Assistente'],
            ['id' => '135', 'acting' => 'Produção de locação/Produtor'],
            ['id' => '136', 'acting' => 'Produção de objetos/Assistente'],
            ['id' => '137', 'acting' => 'Produção de objetos/Produtor'],
            ['id' => '138', 'acting' => 'Produção/Diretor'],
            ['id' => '139', 'acting' => 'Produção executiva/Assistente'],
            ['id' => '140', 'acting' => 'Produção executiva/Estagiário'],
            ['id' => '141', 'acting' => 'Produção executiva/Produtor'],
            ['id' => '142', 'acting' => 'Produção/Platô'],
            ['id' => '143', 'acting' => 'Produção/Set'],
            ['id' => '144', 'acting' => 'Production service'],
            ['id' => '145', 'acting' => 'Relações públicas'],
            ['id' => '146', 'acting' => 'Roteiro/Autor/Roteirista'],
            ['id' => '147', 'acting' => 'Roteiro/Estagiário'],
            ['id' => '148', 'acting' => 'Roteiro/Pesquisador cinematográfico'],
            ['id' => '149', 'acting' => 'Seguradoras'],
            ['id' => '150', 'acting' => 'Serviço de dublagem/Legendagem/Narração'],
            ['id' => '151', 'acting' => 'Serviço de segurança'],
            ['id' => '152', 'acting' => 'Serviços médicos'],
            ['id' => '153', 'acting' => 'Sociedade Civil Organizada'],
            ['id' => '154', 'acting' => 'Som/Assistente'],
            ['id' => '155', 'acting' => 'Som/Diretor'],
            ['id' => '156', 'acting' => 'Som/Estagiário'],
            ['id' => '157', 'acting' => 'Som/Microfonista'],
            ['id' => '158', 'acting' => 'Som/Técnico de som direto'],
            ['id' => '159', 'acting' => 'Tradução'],
            ['id' => '160', 'acting' => 'Transporte de equipamentos'],
            ['id' => '161', 'acting' => 'Transporte de equipe'],
            ['id' => '162', 'acting' => 'Ator/atriz'],
            ['id' => '163', 'acting' => 'Músico/Musicista'],
            ['id' => '164', 'acting' => 'Artista visual'],
            ['id' => '165', 'acting' => 'Escritor'],
            ['id' => '166', 'acting' => 'Cantor'],
            ['id' => '167', 'acting' => 'Outros'],
            
        ];

        $now = now();

        $actings = collect($actings)->map(function ($acting) use ($now) {
            return [
                'id' => $acting['id'],
                'acting' => $acting['acting'],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        })->toArray();

        DB::table('actings')->insert($actings);
    }
}
